fullnameOverride: ingress-nginx-internal
controller:
    service:
        annotations:
            io.cilium/lb-ipam-ips: 192.168.1.24
        externalTrafficPolicy: Cluster
    ingressClassResource:
        name: internal
        default: true
        controllerValue: k8s.io/internal
    admissionWebhooks:
        objectSelector:
            matchExpressions:
                - key: ingress-class
                  operator: In
                  values:
                    - internal
    config:
        client-body-buffer-size: 100M
        client-body-timeout: 120
        client-header-timeout: 120
        enable-brotli: "true"
        enable-real-ip: "true"
        hsts-max-age: 31449600
        keep-alive-requests: 10000
        keep-alive: 120
        log-format-escape-json: "true"
        log-format-upstream: |
            {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent"}
        proxy-body-size: 0
        proxy-buffer-size: 16k
        ssl-protocols: TLSv1.3 TLSv1.2
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            namespaceSelector:
                any: true
    extraArgs:
        default-ssl-certificate: network/gitlab-be-staging-tls
    resources:
        requests:
            cpu: 100m
        limits:
            memory: 500Mi
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMlJ4RGNrdWtXcG9oMTdC
            WW44RVBrMDJDdWVNRUtUbVVUNmttc2J4UkY0CmRnY3BOdGNXTDlMdW11ejFZL2sv
            TUp3UFJvbWYybWE4TFRaV1FYUGRJNWsKLS0tIGlycFJzWnRvckNtZFFIalRCNklB
            SnZYeUE5blBacmROZkx1NUtWaldFdHMKto+867s36ydlhCsnLexA4liqKG9tisQg
            ynulS3b6+RqLIfEeHIMOu8hJXiBmkgN7eFLiPj934Xfxe+sFO1xgmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:12Z"
    mac: ENC[AES256_GCM,data:ARiskc8mOHHADyTMH2J6bjpifCK3VKpKtEH4E4jG1f7JlZDQTb+UPVXlqKFqXnjYb4y+NAbHfYbgy+DLOO4VtOhVkOdKGdXyg7DCiHPi8mcqoGkdvVLkgaLJk+PgdgWQCV5tWCX6w2FesbY+4MKFqGtr3kf1En36GX35f0nJ/TE=,iv:OP5wwEYNqBSCU9bSJgK5PROSBs8v0bS4s52U3EBoKuc=,tag:sKOuKLJAR1ZC90wyjHEP+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
