autoDirectNodeRoutes: true
bpf:
    # Required for Talos `.machine.features.hostDNS.forwardKubeDNSToHost`
    masquerade: true
    hostLegacyRouting: true
cgroup:
    automount:
        enabled: false
    hostRoot: /sys/fs/cgroup
cluster:
    id: 1
    name: homelab
cni:
    exclusive: false
# NOTE: devices might need to be set if you have more than one active NIC on your hosts
#eth+
devices: end+
direct-routing-device: end+
externalIPs:
    enable: true
endpointRoutes:
    enabled: true
envoy:
    enabled: true
ipv4:
    enabled: true
ipv6:
    enabled: false
ipam:
    mode: kubernetes
ipv4NativeRoutingCIDR: 10.69.0.0/16
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
#externalIP:
#  enabled: true
#devices: "end0"
l2podAnnouncements:
    enabled: true
    interface: end0
l2announcements:
    enabled: true
#loadBalancer:
#  algorithm: maglev
#  mode: snat
#loadBalancer:
#  algorithm: maglev
#  mode: hybrid
#  dsrDispatch: opt
#  acceleration: native
loadBalancer:
    algorithm: maglev
    mode: hybrid
    dsrDispatch: geneve
    acceleration: native
tunnelProtocol: geneve
localRedirectPolicy: true
rollOutCiliumPods: true
routingMode: native
securityContext:
    capabilities:
        ciliumAgent:
            - CHOWN
            - KILL
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
        cleanCiliumState:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
socketLB:
    hostNamespaceOnly: true
hubble:
    enabled: true
    metrics:
        enabled:
            - dns:query
            - drop
            - tcp
            - flow
            - port-distribution
            - icmp
            - http
        serviceMonitor:
            enabled: true
        dashboards:
            enabled: true
            annotations:
                grafana_folder: Cilium
    relay:
        enabled: true
        rollOutPods: true
        prometheus:
            serviceMonitor:
                enabled: true
    ui:
        enabled: true
        rollOutPods: true
        ingress:
            enabled: true
            className: internal
            hosts:
                - hubble.gitlab.be
operator:
    replicas: 1
    rollOutPods: true
    prometheus:
        enabled: true
        serviceMonitor:
            enabled: true
    dashboards:
        enabled: true
        annotations:
            grafana_folder: Cilium
prometheus:
    enabled: true
    serviceMonitor:
        enabled: true
        trustCRDsExist: true
dashboards:
    enabled: true
    annotations:
        grafana_folder: Cilium
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0REJxV0hSQWc5WE85TUxD
            cU1hQ2ZoTFo5eVZqK3lNRi9ja1diNXRXZm44CndaTzk3SkxjZTRYNko0UXlPRkdC
            eDVnWGRwZUg2Tmk2clcxSHc0Uk8rcGMKLS0tIFhISWlhYUpGenpvQUh0TVJ3YzRL
            QXhEN29DWjRHTzBrTUVhaHF6b05TSzQKeG3nWmEgcacjXbkcXHWenpTd02P3TaYE
            2G4KOKlNxr6BcnxjupzoXJb9JALNoRWMcNOWc6sz9Ew+oQhvqVbCww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:55Z"
    mac: ENC[AES256_GCM,data:Kh7EVBCjSy+xI+WmEbiMYiKMzK81zWwCn6R7ppgpqHAUEMfqiKJvrXckMVbQjFo95Db1vJjQiBbpPSrIGZAFQTTg02M8t2wmc8tcCuRr/GBQZavl3VoOrWbYaZDQTqphbTGC03Z5v5gEYspI0dSeJH+C/kMlU+kpvgkfInI7f+c=,iv:qvwlqZh73/8hFDOF/0Nvr3QogqeX+brBdvmoejLTZgw=,tag:vPHP+Wn65U8+muHoLoEE9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
