fullnameOverride: external-dns
provider: cloudflare
env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
            name: external-dns-secret
            key: api-token
extraArgs:
    - --cloudflare-dns-records-per-page=1000
    - --cloudflare-proxied
    - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
    - --crd-source-kind=DNSEndpoint
    - --events
    - --ignore-ingress-tls-spec
    - --ingress-class=external
policy: sync
sources:
    - crd
    - ingress
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
    - gitlab.be
serviceMonitor:
    enabled: true
podAnnotations:
    secret.reloader.stakater.com/reload: external-dns-secret
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVnYrdEhZU0FhRCtwRnRM
            YXl3MzQ3QmREN1FEeDdtRTh5WDhMZ2ZValIwCklsUDE2citoL0lYcXNHZWtCTGZs
            SnZVSUUxRnhaeHVPdWlnNnpiUXpoVjAKLS0tIEpWbHBJdmNUbW9MYU4zN0N5UnBB
            ZmhiWXBubFB2ZzJFVGFrT3lId2oxakUKkARLRz3wxoaS5wRDhIZR89qhbRhzohHG
            dCdL8pg8jydUEn3GXd9vubThLb/CMhWjCdJcZ6XqPPg9fNSvxxYNwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:44Z"
    mac: ENC[AES256_GCM,data:rZSVKmr4r3mddkxAMLrcMwPsYKbmiqyQr+NgviYhLaor5YNXRPht+s0n6U0BLZeYJOfhZ+GZcA5upXKPbYsNkjqmKc7jBwj1B7uOlXBiVdk5CA9gpPdkh5Xj/HdM1q3SEcNzD8EipW8AkHeapCmq27ZY265pXdB4KZ12/De8lQM=,iv:/Sre/7ZtEptjdtIFAYIy6NJlwm4ktOGSy0MbnSOeqow=,tag:hirTz/w+eEVmLvd49uriug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
