fullnameOverride: external-dns
provider: cloudflare
env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
            name: external-dns-secret
            key: api-token
extraArgs:
    - --cloudflare-dns-records-per-page=1000
    - --cloudflare-proxied
    - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
    - --crd-source-kind=DNSEndpoint
    - --events
    - --ignore-ingress-tls-spec
    - --ingress-class=external
policy: sync
sources:
    - crd
    - ingress
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
    - gitlab.be
serviceMonitor:
    enabled: true
podAnnotations:
    secret.reloader.stakater.com/reload: external-dns-secret
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TE1rMGEwcGJwR2prMGEw
            Ym0rc001QXZBYnZHVHZTaHFGZVVKODY1K21zCm1GY0RQbDIyQWRNcElYd0lIWDF3
            ZS83VFN0aWw0SXBFdmlhVUFudDNSSW8KLS0tIGs1T3pQcEordTdSNlVGR0IxZlI4
            dzdURVR5dDlxdk5GUlFObS9qWDUramcKCoylC5/xSAM089gwU8Hni96HZTxb0Mof
            Wx/iFURnx0zFVsfrrd8I7Pw4MdhI+jHj6anpfE2/zTKZ31/Odf6JHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:11Z"
    mac: ENC[AES256_GCM,data:0g3QWBxq1ShqTpJFD6zPXXVd+pEEU7AwkeS8kt/717RFg84vWjzo7WSzEgCx+yHA3gXlsNfwO48wPC8z2y0LhSv1gVAexA+vjKqISgrh2bIENs+x/lKTUgqcm97ZrOtZKd21seuz3q6TTbMrnKva34ANwZiX2vxbKmbPHtfN+ho=,iv:DuZ3MDGE/sG3SVGjldzKRQXYBiqC4XYK17lg+ZhtCHM=,tag:TLfOg/B9juRwg2i0BauaGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
