apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:vwQ72EeOOSQUwSYv1O+WuUu2V7NxW20uhYZH0v0SYJ5rwPPippBZ0A==,iv:ZIhDkKwFN2+pIgJukZ+pcY+h5lWyg/hk/1sYMP1ND8Y=,tag:6q/YtLp8grptTkniWtGVBg==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNENUMXBhb1RVRFNzTEJO
            dDlsKzdWVjBqTGt2UERJRE1xRERYQzlqcDFnCnBzQSsrak5JcEh0YjJnYjcxQmlp
            VnNzUzB0bU5INHZCY01paUxNeUVLM0kKLS0tIEd5V0RMTnVxdnlreFBRR2Nwb3k4
            RTBuN2NGTXMrOHVyWExRVndWT3FtTWsKGrJeNKzYZjniNBR1QBBoAjT+tDHibbQA
            ckDsRrKbKCDi7ROnt8cICz7xWNYgSFekRCWkcZ5ZCfsuomcXLIk+pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:53Z"
    mac: ENC[AES256_GCM,data:Nf1JUYtbn3iuGuRj+m/NyO3Iogp/4T+txDMl/2qqKsQvzGk+EKHaZdMTsp7lFs6GokFu7z965LxsidYamIsjWepxDpwp53oNJUYNHAoOiYcpA8Ntr/5JihhQLIdmL1PI2zj48T4XRI7iolSXw7T7ap+6HKOiZBwxPJiwm/WlknI=,iv:JmiQVSc/WotdN/lfxoQBm1QYFBR6VPPIJlO5pXgbWfo=,tag:564X9gpcDDujDl165RJY9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
