apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:SLsEXbKyB9mip3UmG+WzbXEkv+10ERumUOkFpO+Vam1XTTruC5rfjQ==,iv:jnX8QqzkGtlvUDAP5ZBOd9h9mjEO4U4yWKEVnvES5tc=,tag:laIumbra9FuZFzzsiEsxcA==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0L3hjMUZNN0ZBaGlBelhC
            QUUxZTF1NDlBTEVaUzN5ZmgzRGUycDRoZzNnCkJGdEE1WndFdmNRVG9QanVJeXhh
            UCsyUGkyMk16Vitrem1WVlZGaStCWDAKLS0tIDBFOUlUUGkzd3BWckZMcEZqNEZM
            alZETmtRQ0ZJY1FzV0xOd3hhTGdYOFUK7p9qvu/q67jlZzc1nVmpuTpf/fBLKWg0
            QofFk3mwFUvjY8OJBZ2FwpIHdzzpXbqU8XRU7QmL/rqDZYMb6kW88A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:11Z"
    mac: ENC[AES256_GCM,data:aFx28Arx5jzEG+pEcXTOUmflHFZCPT/qb0D7yFp+CCCFsLvEs1KA5uGSwVAYQkWuGJtwvvFcYX8JkTj693HYrU94jKnIvcJtSBEpdGITHXIKYe9F7DpVtpBpCdhpBHJabbwmM1kIpHxV/sDTkQCVPF4KiowyQ2uIoefB75FI9Gk=,iv:Clm+89ccCVKncL+UdO2EYefAzr8echd37hL7G6TBip4=,tag:05jB226yqZAX0VNMzWd9Hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
