apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:PuOhmAE2FjaIgj8PhhmzFCDHPtzoXAIrDnS6YmZgf9vhqw5LO7DI/g==,iv:KImOjUeSMJPp0jY20fiHEw9aFAix38zJ3/Y9T/y6j5E=,tag:kZhTyyYhv/ZPGUMvFJy60w==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RU51c0gxcnFxWUUwK28x
            UHhabytSUlhRbjN6cWJvSEgzdElpK3J0Vkg4CjBPUFMyZlJVcFNSUnBoc2YxZ0R3
            MG14MmV4dnZja3BsQUN2KzBZWmQ3VFEKLS0tIHFoekR4Rk1PWEJGdTFhWkJ6S1ls
            NGgySDExYWQ3Q3owc3pLSjIrS2ZJclUKYKGdSaYhQTCn01XfJZ79TtnpE7Hyie2j
            wQmTenOVBYnLC5P0PcfLbsfkAgWA3ap8D55ohwIVp7LzgAaZrXlxug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:44Z"
    mac: ENC[AES256_GCM,data:BUIPqRigKfniHbLUkhrjcoP09alWb23xk6uwd6j6dbgZn9hhekP/+KWmgjFy+84wbZrurfBPw61NrSApegzuRF5qEo4AhUPNLGgFFvjVon1vmPuluGUIXJymKRxlKXWnqBcIE0sLAPQQi1oBP9yfachiwEPTp2mI9vUHRa7pnBY=,iv:N+vmWaCRs0uFJTVVGN1FyxRa0zy5kPVZ1xJPICyNJF0=,tag:eUbS00C7vk0YqdSugUKwPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
