apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-staging
spec:
    acme:
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        email: enicky80@gmail.com
        privateKeySecretRef:
            name: letsencrypt-staging
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cert-manager-secret
                        key: api-token
              selector:
                dnsZones:
                    - gitlab.be
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a292N0dKbzl4am5ZNWZS
            MldFaU8vV0J6MVRObmNNRkpnanRKTTgvZjFZCk1SSXNQOWpOTDZrV1Y4SGZJcEN2
            dDE3Y2F5c3VJVC9XZWFTenRpWkdqR0kKLS0tICtZWVplcjFkaE5QUkUrNkQ1aHRy
            cUxvU1VBZVdPQm0vYm9IU0VUNEQ3TncKlCQCPWUSChKNO6IxUMVBTR9BD4GbAw9F
            G9zCa/lJJ1weTZj3L2Aq8RkajNYv9r5fP6NHtUhCBoABENlCAZtqlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:11Z"
    mac: ENC[AES256_GCM,data:ieKOxa6GpE5/SLRiY7av1NNVkGe3CTcZdaYjjIdPQCsUE3//bPQtD8GiVFM9Lf9fRt1/eH+x1yMljt9Yq9UntsP++5rgq+Dfh2MfnKfnUGum/vJ/zIF2433eyZ1hllgB5inSrg7QCSQ1BjIA1YpXHlY6mZ3n8VquAJ7jw+RDDYg=,iv:LPRc7lZxl6MkAVi5gLOmV+OHwrpDP0tb3dZRZfa+L9E=,tag:h2RAJ5uXxqdXjexa2DByWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: enicky80@gmail.com
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cert-manager-secret
                        key: api-token
              selector:
                dnsZones:
                    - gitlab.be
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a292N0dKbzl4am5ZNWZS
            MldFaU8vV0J6MVRObmNNRkpnanRKTTgvZjFZCk1SSXNQOWpOTDZrV1Y4SGZJcEN2
            dDE3Y2F5c3VJVC9XZWFTenRpWkdqR0kKLS0tICtZWVplcjFkaE5QUkUrNkQ1aHRy
            cUxvU1VBZVdPQm0vYm9IU0VUNEQ3TncKlCQCPWUSChKNO6IxUMVBTR9BD4GbAw9F
            G9zCa/lJJ1weTZj3L2Aq8RkajNYv9r5fP6NHtUhCBoABENlCAZtqlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:11Z"
    mac: ENC[AES256_GCM,data:ieKOxa6GpE5/SLRiY7av1NNVkGe3CTcZdaYjjIdPQCsUE3//bPQtD8GiVFM9Lf9fRt1/eH+x1yMljt9Yq9UntsP++5rgq+Dfh2MfnKfnUGum/vJ/zIF2433eyZ1hllgB5inSrg7QCSQ1BjIA1YpXHlY6mZ3n8VquAJ7jw+RDDYg=,iv:LPRc7lZxl6MkAVi5gLOmV+OHwrpDP0tb3dZRZfa+L9E=,tag:h2RAJ5uXxqdXjexa2DByWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
