apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-staging
spec:
    acme:
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        email: enicky80@gmail.com
        privateKeySecretRef:
            name: letsencrypt-staging
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cert-manager-secret
                        key: api-token
              selector:
                dnsZones:
                    - gitlab.be
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMldTcmc4V085TThHVzcv
            RG5aNW5VYUVtTy8wbmhNaUNaWEVZUjN3eTF3CjMySyt0S1BZdzZocUtCUVhDVHc1
            WkdRQzMwa0VVcC9NM2JHQVkwZTFhWU0KLS0tIERyQ3F3OEhCVmNQcnhrdVdzVitP
            aExHSkxzY1A2ZkJHWmFrR3dHNVZ0U1EKiyTrANifJUOmrZBXwJ/VMe1GzUjDAhhn
            hJk+1SUK5DX3/Zoh4n/BdECe6W4ZNX38O1kuRedZpIBC/0zR+i4Nnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:53Z"
    mac: ENC[AES256_GCM,data:XcwcZn+ysaUiddstuQLtX71GDNbN7ASgcmxqUn0ZI6++OWgW3AT9/IYkwjVxlgC2oK9cj1jzYMmp95YRGmIUChndxsERWjgvuOTL0AH+SXTQGjgCRj/j9ySCiFWr5dAdJoKv3P9JSnq2FlOrtMb5XZIwnRnJGAp3h1uEjqPa7dM=,iv:/8tMlYRT4/CZB7W05J6ukaM0uO6QqmfvsDZA3wUC1Lg=,tag:tEkaBBQP2x/9k4AF9zFXrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: enicky80@gmail.com
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cert-manager-secret
                        key: api-token
              selector:
                dnsZones:
                    - gitlab.be
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMldTcmc4V085TThHVzcv
            RG5aNW5VYUVtTy8wbmhNaUNaWEVZUjN3eTF3CjMySyt0S1BZdzZocUtCUVhDVHc1
            WkdRQzMwa0VVcC9NM2JHQVkwZTFhWU0KLS0tIERyQ3F3OEhCVmNQcnhrdVdzVitP
            aExHSkxzY1A2ZkJHWmFrR3dHNVZ0U1EKiyTrANifJUOmrZBXwJ/VMe1GzUjDAhhn
            hJk+1SUK5DX3/Zoh4n/BdECe6W4ZNX38O1kuRedZpIBC/0zR+i4Nnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:53Z"
    mac: ENC[AES256_GCM,data:XcwcZn+ysaUiddstuQLtX71GDNbN7ASgcmxqUn0ZI6++OWgW3AT9/IYkwjVxlgC2oK9cj1jzYMmp95YRGmIUChndxsERWjgvuOTL0AH+SXTQGjgCRj/j9ySCiFWr5dAdJoKv3P9JSnq2FlOrtMb5XZIwnRnJGAp3h1uEjqPa7dM=,iv:/8tMlYRT4/CZB7W05J6ukaM0uO6QqmfvsDZA3wUC1Lg=,tag:tEkaBBQP2x/9k4AF9zFXrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
