apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-staging
spec:
    acme:
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        email: enicky80@gmail.com
        privateKeySecretRef:
            name: letsencrypt-staging
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cert-manager-secret
                        key: api-token
              selector:
                dnsZones:
                    - gitlab.be
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMUtCODFQcU0yMnRZdGsy
            RjROekFld1llVFB4cGRvdk8yQ0h1c01TaUg4ClNmbWpDb2FYRlJHeTg5am84dDJx
            eWdkcklzUFVkeEFLbHpSU2Vwa0w5MXMKLS0tIFJrV1NGSU9yVWdVV1FvVUZSREdH
            TWZkeFVHbVFSb3NOWkVacGtwRzRKL0UKC7y3QFhdIphwuWCoLmgA8+9qDzrQN/g+
            OzZDLlnQ1j1gHib9rffoZCj36n221p8PTUIvDXz9BCuY/UpxYsLq4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:44Z"
    mac: ENC[AES256_GCM,data:uj6SGVIu06GiXcxTKjjvKynGELPvolxOC4Nz5akcUd2OwsVogVnqH89MifFGZXa3ioGNYlVlcQGRY/epQzSlmTClrSM6CZbprrNOu1LqTma3zT9Mu/+h5/kX3Ns3h+ozU3Pmt1eiTyRy5G7dOxQok0AH0l37fMSl5mZZEDKCLww=,iv:SJ8ouOEwcDE9SrGjMUrU42Uo+wnUMRL8yeGi9WLaT9g=,tag:LBAbqqPGDmrJ2JnX8gJI1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: enicky80@gmail.com
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cert-manager-secret
                        key: api-token
              selector:
                dnsZones:
                    - gitlab.be
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMUtCODFQcU0yMnRZdGsy
            RjROekFld1llVFB4cGRvdk8yQ0h1c01TaUg4ClNmbWpDb2FYRlJHeTg5am84dDJx
            eWdkcklzUFVkeEFLbHpSU2Vwa0w5MXMKLS0tIFJrV1NGSU9yVWdVV1FvVUZSREdH
            TWZkeFVHbVFSb3NOWkVacGtwRzRKL0UKC7y3QFhdIphwuWCoLmgA8+9qDzrQN/g+
            OzZDLlnQ1j1gHib9rffoZCj36n221p8PTUIvDXz9BCuY/UpxYsLq4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:44Z"
    mac: ENC[AES256_GCM,data:uj6SGVIu06GiXcxTKjjvKynGELPvolxOC4Nz5akcUd2OwsVogVnqH89MifFGZXa3ioGNYlVlcQGRY/epQzSlmTClrSM6CZbprrNOu1LqTma3zT9Mu/+h5/kX3Ns3h+ozU3Pmt1eiTyRy5G7dOxQok0AH0l37fMSl5mZZEDKCLww=,iv:SJ8ouOEwcDE9SrGjMUrU42Uo+wnUMRL8yeGi9WLaT9g=,tag:LBAbqqPGDmrJ2JnX8gJI1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
