apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ebgAYiVWxBEUhpsi28JKGKpKXZabbss+e5JMyf8J8F40dC1L4mZIpA==,iv:djTgIbQiPxfU5AxebCn1VB/aXxAJl4GLUxY3YSs1frU=,tag:LVqjWsVpPEbG/A1nak8ePA==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b1NhWmgzZ2R6TWtYSE5j
            VENiczc3T1lUSXFFcEFNSmZMM0phRDlTMDI0CnZRblJYRC9NalJXektRSjlwSnpU
            cmFNak5YUzR0cjVCbVRGQ29PcTIyUlUKLS0tIFBNNGw4VEhHUVJLdGF5KzQ5UHl3
            MmhWUkxRdWFXek5qQk5mWEtVZEFVZGcK32e3HstNDcNncyUaE5IIcupyUJfWlGiz
            voBunXxyCc2C+QyLKOQpFn28hXr0196YGYBZVlG0wIDtHC9IRBktIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:44Z"
    mac: ENC[AES256_GCM,data:lq9kssStrk65ZynNZ49d7d+CEiuCgwcmFI6jmvP6VRNaGsN/3udmApMMMlm4Y9jIYYcsGJd68kDhhXZW3Ea6UKBuJI+Xoor9PfeXi8orkiYltwv3O/JFmOIfGHqB89jJGVSId85pegz2WUHvAueWFTOeTkajlnVjBZ6J1bZ2EwU=,iv:DBM1x4EHtAWj5DNnnRMpbbGdNIaIp93ZumsJwx6+cZo=,tag:nJWNMEH003mtcBZLcLcJOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
