apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:b87b57fdxH7k8mHcmp6rXrOdZhat7/qbD9aaoERLYdXnCvdcJGodCw==,iv:DoaUWQVjV+9F9OGudgHONSU1MgS018K7ujqQvfHO0ZQ=,tag:gkeQVPR7OWsUBCBVsGdG2g==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0RWcWFUbHIyQXVuSjJp
            Nk96d1JoaGx0MG0vcDZ5bHdBNWhqNmZ1WVZJCjd3cDUwRFJpRHRBazNEdVAwMkVC
            RkdRTWJTWFVvNFFOcE5Lak12ZWg5L0UKLS0tIHBHRlBBUGdBSHNRNldBYWZ1TGpO
            T3U5K1F1MFprMzJ3a1NYNzUrNkRJZmMK4BwwYo6sqR17gHHGUQGLSFc5sJ2esiLd
            CFehrusXdaY0hO34xHfDu1/ja/ZX952TEiG0P3VPh/VGRr/KQf9pww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:54Z"
    mac: ENC[AES256_GCM,data:rHlv1mCJ44wOfyb7ThPJ+YIhCfQ/XrBVFk4Pq3ca4vHzOajBV7sq+SE5jboVLQMSHYaBF7nCu5hir/XCKXf/oClc0cP6f/3YTclpbog2Rwx5RPs8enbBF2g7g8cD8kQDrNC5ir8NPO892xTbC4S8D9RDGnwxef3n+tOWiWgh7OM=,iv:Togee6Kxah7Qs0ue8h3aKz1Pv+p3YxPQVPgH6R3ha7I=,tag:88yS/9BOuIq+QeoxZZDJvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
