apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:L7yibqFUvQSd/0hF1j2QlzKZZL7GWcxex6PU4b/K9OZw6crbvw3lWQ==,iv:llDyJY94QtqZDXWUpRGNB6Nau1+c2doivCrFGkWvfSI=,tag:sSOeHlhCRL4SQw8o7i05hQ==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaGljNDNrc1pBS1hzK1Bx
            dWhrTllDRXpBZ2I4SnFLeUIrYVA0VGZMbFVVCjVrYWFmN1VRMEZqVGs2VVZYcFU1
            NG5NbHdkbjhYS0ZOR2RyaGhuYk1iSXMKLS0tIDdieVBUdHRySVRibzZRdWlDd3hM
            d1luZjdVN2x5eGFGUW8yU2FjbnpsUncKpYvepBUZGAhsB8khZZJ2g3G/voxRaIii
            82eo8vI9PGkCXwcu2lC+zjj59r9h6Mwy88iRWZ36KA9z/QK9y6Ie+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:12Z"
    mac: ENC[AES256_GCM,data:Md2AxhpsOi07iU2WObUYcLhwmzkFlTNA/Drbvi7QdqB3NTa3iyW6wZLUu5nP71HpKihsHsJfRMV4ieh+z/92TONve1UWS+qojAyMK4BQZYTkhZzramYATyt+04jTBD44gKvzubcEGrvjWztiEubp9PrZsOIrgWbxO0EzqOa2kj0=,iv:LXrGgNDCesx6m8bSIfMLNwKwPpMIrhMM/AlI3I5+xMY=,tag:0+nqw59xoSlQ1XQuNcowJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
