apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: gitlab-be-production
spec:
    secretName: gitlab-be-production-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: gitlab.be
    dnsNames:
        - gitlab.be
        - '*.gitlab.be'
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVFpuNERRMnFibDEyRFRC
            NFhaTkdIb3NDVTRhUDk5RnlVd2RQVm1IcVQ4Cjg5RFFvN2dCcnVNRzY0MGNhZlVS
            ZVVNbnJJNTRyb2xKU0dMSkx5UEliQkkKLS0tIGJmMW05UnRkUC9pT1hYR3A3T1dr
            RUdQZXpiT1dXZUJMUTNYS00wTmVFYXMKyRyTf+4FAcuUvS9jgx5IjxfPLQojwOlK
            9JRuwhME/h2v5AV7NokhVit9YOX94dlEOOzIyzHvCWdWB/eIMqsThQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:12Z"
    mac: ENC[AES256_GCM,data:S+mvJ4QAMM/FhjRr67CMRaplXkwhGklyXlZC4xnEEvPD+xpMLfd+WscFYvU4ydqbIAKvm4CBdIktbbz3nWCNAgP2TrAbBlgYvCpJTkHCO3INJJcd9vT5fhatWPsBuvFH1whUf1o2+CEjUqOy3zQwL87Umr6Iu+PLhPVZ3eM1hl4=,iv:CGooBnjRC33o1TEdd8JjD13tht3dwutFShVb0QxRrzI=,tag:Vy7RYM4G28/8ZkbWAl7WEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
