apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: gitlab-be-production
spec:
    secretName: gitlab-be-production-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: gitlab.be
    dnsNames:
        - gitlab.be
        - '*.gitlab.be'
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NDBlYWlpcUloVjcra3lJ
            VXJ3M0puTzJ5cDVOVWIrMUJ0c0IvTElod3lvCjRseDRlZ2dKYWhrbVRoRXAvRDg2
            REZMSzVwRTY5dzhuVEVQS2loV2loZE0KLS0tIDRPaENQMTBrbFV1S1poc0UzVG1K
            SUV6K29zM3MweFdFbGZnWWxvVGRUYmMK4XlBMdbOEceKsHnI/Bv6j9LM+zbnOKBj
            PXhnNGP5EnOateMe6Pmsi66ozS7IDM+UnDl68DE/DxFZlAVFAo5CQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:45Z"
    mac: ENC[AES256_GCM,data:DIVsb2oFsGQoiQwbbiMhSvU9GiJzlyTkcVjCDDzrD6jJp4DuEWMPQA7itPXRJjzQS/d1NgUqr4D1+PjwCe4kNbJQ5C/YMc6vNDjhTnLRrMsiqOKYBFblC1kDdUe11XzCvrF26uURQJCqiv5Uo2Wd6gwbpbjNAbGoimDNfSJTPM4=,iv:EQ47HpEugT3rS0l5eeBxepWtCpjZ1D2idWlTbiz8jDg=,tag:NFjsHQYTcicSFlnoy0aeOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
