apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: gitlab-be-staging
spec:
    secretName: gitlab-be-staging-tls
    issuerRef:
        name: letsencrypt-staging
        kind: ClusterIssuer
    commonName: gitlab.be
    dnsNames:
        - gitlab.be
        - '*.gitlab.be'
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUmFlRjJkSnk0d0RSaWlz
            a25CSGNnOUVKekxZWE9XQ3Z6VTVPc3Z5S2lJCjJWUW8wQzlZNHQxU2dRdmVLbTNM
            Q2NhTnFrZVR6Zy9KNzFSOStKL1dMZmMKLS0tIFlwQjFNVVJEMkxBNkNMOVFnOVI5
            S1BsYVVkZyswYnNMQ1NtazdPVmlzd1UKPB8/LKRSrIsq3bMzDataWDAs65KrZxog
            kzH5qMuj6jgXt5ZVcVWbClQDl8APZV+Tu2Qu/y+dC1TaGLyRIfBJtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:12Z"
    mac: ENC[AES256_GCM,data:tE53gxtY/PWcnJcrz4HTHDGj9a7SYwol/0i6FD2VgeAhoq3plGogZ0iDODOjx+i7ubFSOZRYQhhNO9Ktw36Z06+JHg7tZwvPE++/OTxiF0iRNjDGKG+14a7bF3pmhxXvzYMvXWDUxz+IRxy+/TMEkHnnV2yicEUWVNR+gYE8JpU=,iv:v0llD5lPDHJpYg31d3FlZjycWzbzibnppTb1287R70Q=,tag:LOnrHlHdTSrlwjimSyuHBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
