apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: gitlab-be-staging
spec:
    secretName: gitlab-be-staging-tls
    issuerRef:
        name: letsencrypt-staging
        kind: ClusterIssuer
    commonName: gitlab.be
    dnsNames:
        - gitlab.be
        - '*.gitlab.be'
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZUhxRThMVklNcFlVaThV
            MzRMcGV5VHlTTzN1c0ZBc3RDSWNSNlFpM1RjClZYVFlnVXhDTXpHbkVDaFdOV0JP
            RUhmU2IrNGM1MS84dktrbTg3TUVLOXcKLS0tIEUvVGNsaDVMZ2xvQlAzQVR6djNy
            TnZoZDRSM0RVWGxaby91K2pHWW40UlUKZhunWCZJFY6G6AOTc8SaNFy6QngQ45VC
            qmfdvrf7Tpv9jc5NLAgq3D6GMmy4ye/K3bkyym5p3TrV/2UMt1F3rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:55Z"
    mac: ENC[AES256_GCM,data:fTKTHZH0GQEDdEDktLJozvB083FBpNugERrK/YLlPOzVNpacX9Pb+qKiPawYUFiU5YDoWAEEmM2uLKEqb2q13QHoSJFpzUMyXcQkBxtw8JaUn/oxTJ55cfHMMvpfsDl418KvhlM8pFDhCsK3BDjtapWYjyguzt7tMyi6KXw2BWY=,iv:inyixadNt4+yQxo/IWJR4tYThvI61qMsQO991nuHRZ4=,tag:AndFsT9Li/9qmiRGrZDl5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
