apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: gitlab-be-staging
spec:
    secretName: gitlab-be-staging-tls
    issuerRef:
        name: letsencrypt-staging
        kind: ClusterIssuer
    commonName: gitlab.be
    dnsNames:
        - gitlab.be
        - '*.gitlab.be'
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeGwzazNFUUo5U0tMU1pS
            VFlETVBOTlZKWkJVQWpkMXlmUUx5aXgrZXhnCms4ZVR0Qm9QMGpLa0VNYWFFNUxT
            cllGRU1VN3RnNWEvVE1EYlNScDJaYU0KLS0tIEJJNDR6ZFQrRE0yRUFHVW9ZMWl3
            WjlibEdNT1lJNW1mNDU5Zm51cU9Rb2sKZsuHlPZ1VTJGnG8SBbZtIBPOiaJb/G2y
            +JQxOhBjou2A24Xx7pFY7JcXsGsRXjyHo12QZUJNEyDH0v/RGsbfDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:45Z"
    mac: ENC[AES256_GCM,data:F2B/xy+BVHeSS6TleUFVHz8HP94qN/KO89FRTpCTPGo3rLJKJ4of3YSNIZgOYUL4VjEZY/AtXV4XjZiXNvtXvGOFgTbKYnS0e7zSGd1wVsOJf8jnfJRpnadILC88zVbFh7BFMha+fnafKbZrId6PRQAc2h9Gzny5slqLUWLSX2E=,iv:3V3iI+E5FYMrR2vNJ7G4KwHcOsskVXYEWeWlfkZ0828=,tag:nry2kERStCAhJwHDc+YdCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
