fullnameOverride: ingress-nginx-external
controller:
    service:
        annotations:
            external-dns.alpha.kubernetes.io/hostname: external.gitlab.be
            io.cilium/lb-ipam-ips: 192.168.1.23
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
        externalTrafficPolicy: Cluster
    ingressClassResource:
        name: external
        default: false
        controllerValue: k8s.io/external
    admissionWebhooks:
        objectSelector:
            matchExpressions:
                - key: ingress-class
                  operator: In
                  values:
                    - external
    config:
        client-body-buffer-size: 100M
        client-body-timeout: 220
        client-header-timeout: 220
        enable-brotli: "true"
        enable-real-ip: "true"
        hsts-max-age: 31449600
        keep-alive-requests: 10000
        keep-alive: 220
        log-format-escape-json: "true"
        log-format-upstream: |
            {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent"}
        proxy-body-size: 0
        proxy-buffer-size: 16k
        ssl-protocols: TLSv1.3 TLSv1.2
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            namespaceSelector:
                any: true
    extraArgs:
        default-ssl-certificate: network/gitlab-be-staging-tls
        enable-ssl-passthrough: "true"
    resources:
        requests:
            cpu: 100m
        limits:
            memory: 500Mi
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dEllcGVuUnlrSzRQM1gy
            QzcyTVcyejlyUGY4Tk9tTjRxeXNscHFuTmpRCnViQTlyQ3Y0cjRyZjBuNFk3WHBp
            VFd4bFRvYmlWTmFvelFVclhucUJBN1UKLS0tIFVLMmZQYksySHJXc2FrUGE0RlRI
            MEN0MFp6M2cyS1ZFbVR2NHppdDA1ZzQKDUNmbTQQwvCRXbsLIfCu+L5JxW4/03wn
            TLS7UQTHJr3ZV6ah1f907BYQoCwkt7B6TrSMfaAua3d6OtPmK1MG3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:45Z"
    mac: ENC[AES256_GCM,data:9mKe3hdXNHzSEwnAN2LLNliUuumVbfsJ24FBRJ0piQ6omBztPiTmK4QEH8ENc75cFoxwx507HSubRIONXE7RKkuyXL4j0G8AGBYE3yf8oIFVF2v83dphgmolbepz5J+cZR1R4rCiZilO1XUH/9To38+tAJBTGhqqVyhIvybbz84=,iv:JK88a+E/4/vigqHG8S0Z0Oaye/2xhNZVP+xhg6V70GY=,tag:ck4zhFvYTOlbNb608n/w4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
