controllers:
    echo-server:
        strategy: RollingUpdate
        containers:
            app:
                image:
                    repository: ghcr.io/mendhak/http-https-echo
                    tag: 34
                env:
                    HTTP_PORT: 8080
                    LOG_WITHOUT_NEWLINE: true
                    LOG_IGNORE_PATH: /healthz
                    PROMETHEUS_ENABLED: true
                probes:
                    liveness:
                        enabled: true
                        custom: true
                        spec:
                            httpGet:
                                path: /healthz
                                port: 8080
                            initialDelaySeconds: 0
                            periodSeconds: 10
                            timeoutSeconds: 1
                            failureThreshold: 3
                    readiness:
                        enabled: true
                        custom: true
                        spec:
                            httpGet:
                                path: /healthz
                                port: 8080
                            initialDelaySeconds: 0
                            periodSeconds: 10
                            timeoutSeconds: 1
                            failureThreshold: 3
                securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                        drop:
                            - ALL
                resources:
                    requests:
                        cpu: 10m
                    limits:
                        memory: 64Mi
defaultPodOptions:
    securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
            type: RuntimeDefault
service:
    app:
        controller: echo-server
        ports:
            http:
                port: 8080
serviceMonitor:
    app:
        serviceName: echo-server
        endpoints:
            - port: http
              scheme: http
              path: /metrics
              interval: 1m
              scrapeTimeout: 10s
ingress:
    app:
        className: external
        annotations:
            external-dns.alpha.kubernetes.io/target: external.gitlab.be
        hosts:
            - host: '{{ .Release.Name }}.gitlab.be'
              paths:
                - path: /
                  service:
                    identifier: app
                    port: http
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbDFhV1Z0dlovZjMydWhG
            K0x4M2FpSFhyV1o0MkZsbUx1Uk9tVml6aFNFCk5uUXB6TS9EZkRQb0U5Y0h0Y1FL
            UDNkcDhCRy9hNk9qeTg5M2pJRVM5RVEKLS0tIFlDQTN5RFhQZ2VVSmVZVUxJeDJx
            cmx3UUxJNnA0V0JRZmxxZHRCUkF5OVkKd6hZ8ScvuS0cL0rPFRbMoVbFImXq7LHj
            IJRO+Kzjfwr4J5PyL2b0tdwNyUD0oTVQUM8Cm36RS7MkjAw35OuZZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:44Z"
    mac: ENC[AES256_GCM,data:nLzdKegGG7yY60FYsAXOUaqDpIzBqKF2INJPt4OSM5Zzhpnt7ee9WkJF1kn+wS2fjr9Wbogj/1RGqFZIF010/2Q6oTCHa5w8Ik9jwEpgPjSAGrI9rTyEkYGFmLtGzGifeqQzlWSp4pWSNe6yJTtjlJzRscJGx9Qi/22btqKD1T0=,iv:gTAhDRNS0jLBjCCAsECdVVbbVBG2CrltmhZ0OcGjVdo=,tag:C1DctBHzu+4rmbk25GucbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
