controllers:
    echo-server:
        strategy: RollingUpdate
        containers:
            app:
                image:
                    repository: ghcr.io/mendhak/http-https-echo
                    tag: 34
                env:
                    HTTP_PORT: 8080
                    LOG_WITHOUT_NEWLINE: true
                    LOG_IGNORE_PATH: /healthz
                    PROMETHEUS_ENABLED: true
                probes:
                    liveness:
                        enabled: true
                        custom: true
                        spec:
                            httpGet:
                                path: /healthz
                                port: 8080
                            initialDelaySeconds: 0
                            periodSeconds: 10
                            timeoutSeconds: 1
                            failureThreshold: 3
                    readiness:
                        enabled: true
                        custom: true
                        spec:
                            httpGet:
                                path: /healthz
                                port: 8080
                            initialDelaySeconds: 0
                            periodSeconds: 10
                            timeoutSeconds: 1
                            failureThreshold: 3
                securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                        drop:
                            - ALL
                resources:
                    requests:
                        cpu: 10m
                    limits:
                        memory: 64Mi
defaultPodOptions:
    securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
            type: RuntimeDefault
service:
    app:
        controller: echo-server
        ports:
            http:
                port: 8080
serviceMonitor:
    app:
        serviceName: echo-server
        endpoints:
            - port: http
              scheme: http
              path: /metrics
              interval: 1m
              scrapeTimeout: 10s
ingress:
    app:
        className: external
        annotations:
            external-dns.alpha.kubernetes.io/target: external.gitlab.be
        hosts:
            - host: '{{ .Release.Name }}.gitlab.be'
              paths:
                - path: /
                  service:
                    identifier: app
                    port: http
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WkhUUUJicmNhVG5xT1po
            UlRrdkk4TGZ0V05pQXpjb280ZWRCV1Q5RkgwCkYvWGhlOVdkeHB0VHYwbGFsem1v
            QUtpbVNhYXVmaVBrWEtVYlk1YkZwS0UKLS0tIGdzMXJUd0pRZXNxQ1IrYTFJZ3RU
            eTdCMGR1eXN4M0NvbXE3cFdnaE1CcFEKdp6nf4IgH8IHUiLzIoI0Xes7ADokaSBh
            ldlnd90y6tFrtrP3MhgbbpiKr0nHzWVjETC2slA1MenTiqvgxmmcsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:12Z"
    mac: ENC[AES256_GCM,data:XTlq08dIYs6BjsiTLIzZDf6b1CPLnfVySwLVEIpinErdk6ufMSvZzF61nL+kAB3Pg1DuO5huolXw926s/PtY3TqehuWHUL2yZ11z0Z0iZ14PWDYAVLoh8oY0AihpiLdCrTCuJcJO+sF7G0yOyXxV/jeMa1aP633sAJYJWwRi6I4=,iv:iYdiODr4cto55Vebm9TDaZFGxFhpbR3RUK79ZttqPJ8=,tag:4KKKCCr1D0qoVT5Zyzx18A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
