controllers:
    echo-server:
        strategy: RollingUpdate
        containers:
            app:
                image:
                    repository: ghcr.io/mendhak/http-https-echo
                    tag: 34
                env:
                    HTTP_PORT: 8080
                    LOG_WITHOUT_NEWLINE: true
                    LOG_IGNORE_PATH: /healthz
                    PROMETHEUS_ENABLED: true
                probes:
                    liveness:
                        enabled: true
                        custom: true
                        spec:
                            httpGet:
                                path: /healthz
                                port: 8080
                            initialDelaySeconds: 0
                            periodSeconds: 10
                            timeoutSeconds: 1
                            failureThreshold: 3
                    readiness:
                        enabled: true
                        custom: true
                        spec:
                            httpGet:
                                path: /healthz
                                port: 8080
                            initialDelaySeconds: 0
                            periodSeconds: 10
                            timeoutSeconds: 1
                            failureThreshold: 3
                securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                        drop:
                            - ALL
                resources:
                    requests:
                        cpu: 10m
                    limits:
                        memory: 64Mi
defaultPodOptions:
    securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
            type: RuntimeDefault
service:
    app:
        controller: echo-server
        ports:
            http:
                port: 8080
serviceMonitor:
    app:
        serviceName: echo-server
        endpoints:
            - port: http
              scheme: http
              path: /metrics
              interval: 1m
              scrapeTimeout: 10s
ingress:
    app:
        className: external
        annotations:
            external-dns.alpha.kubernetes.io/target: external.gitlab.be
        hosts:
            - host: '{{ .Release.Name }}.gitlab.be'
              paths:
                - path: /
                  service:
                    identifier: app
                    port: http
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Uzg4QUVVTldwMmF1NHRq
            am1sRG94a2ZoS3VYVHdQdHVCWVQ2RzFHT0NRCi9ITVdIY3M2L05HbW5WWGtJNmx2
            Q2hWZUtDRmpOK1UwNkU2b0pMUDdaV3cKLS0tIC9aVFl0YVIvS2hoWnIvNFVmWkFZ
            Sjh4LzFxZDg2ZERCZDdqeXBXL0NFTUEK/MMGIZDPjofdFWX8fUscONhtCD6Pcrei
            706Q+FJi/IoaVnNTrFaxiUIAtlTCxhnmOdqcdTipXMY6nUI1nwaXUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:54Z"
    mac: ENC[AES256_GCM,data:LYiWDQG2UpVH/1gZ7/9Mp3t+Cphq4pKNyE/hQb8czOlSVNMfzEeTbiZqwgqT/dN5KxZAx94w4LdyVmPevYsJh96FbTVsBByuJr/hd96rwd1H+A2HAZ9CF7CLopaU0JMGeJRrMpBkFRs7CHBp0dVjOUIVo62Pv8mFUnX+y/RVIxc=,iv:GcgrbUxiEOXZmSmOASqW/7+jDg6ekbXG+tHNvBlOJ+E=,tag:xcpWTIu+4BXRJfsQmHP0eA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
