ingress:
    enabled: true
    host: longhorn2.gitlab.be
    ingressClassName: internal
service:
    ui:
        type: ClusterIP
defaultSettings:
    defaultDataPath: /var/mnt/storage
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSHBTTHo0M2Iyd083TEV2
            ZjdwcVZYcElINFRhZC9udmRTSWlVdWFJcVdzCjg1YzFVRkZVQnRKbzZ6UmIwUU9n
            SjRJZGl6UmxRNjFjNEVFSVBFbGlJL0kKLS0tIFJGSXdVNE53ZXdyaSt1cHFnYUZP
            WUx4RzlMY2xmUi9QaGVRVlRNdW91U2cKE2hl6Zz4IbUpami/hxl7X1XmP4bO0dGU
            6O3NUkhsDXs+W09ldvAHFIoJbU+g1I7rj95n/NiRQjCJsj36KpTq1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:44Z"
    mac: ENC[AES256_GCM,data:wI5ACMBbDgusLyWnwdaGswIRU/gpoqxh8Ggz4TgtPVZl2AO9Fd+PbKhTjFmfHjscXQlePzrakpjiVCwff4mvo0OPRohbR+okzpp6X66p863jBepceocTDs5/W5mZkN+Sen0rRILt8KyjKA2aw3lmxJxXZt90cjPHN8ibCIY64Bw=,iv:NT60uFIVQbo94/Dm0caDJte/zGMQ0f1MLw/Wou9ubLc=,tag:KHpTsKNouQ25qhf4379JLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
