ingress:
    enabled: true
    host: longhorn2.gitlab.be
    ingressClassName: internal
service:
    ui:
        type: ClusterIP
defaultSettings:
    defaultDataPath: /var/mnt/storage
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMHFacmNpaVBCSzNUcmdO
            MXp3aHhhMTVtTEdDVUZpNXBTdzNWMnJsWkF3ClpMUjh1V0RNR01Zdk9RWjVTclgr
            YXVZdExISmw4NHlJWFpNc1RMa2M5UzgKLS0tIE5Cc0tEaGxSakZKS3p3M1BjUXdz
            WjJ1NmI1SU5OL3RFNll0ZC9RaVNvWU0KgXKOuoFl3Xa3mQ8sSV+ZvK8WYLIoHEOF
            s9eljOgrxgs1tx+42yN+WHRvHOsx+7E2YdrwtajpLMR6OQEmywaBWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:11Z"
    mac: ENC[AES256_GCM,data:8bSl8XijBFhU0pWjc9yr+aVIF65pGbJTHGuAa6cJ09guCXC+gCmptpwfrRxKEzE++D1VJNv/XNwX7NukF8j006613S8xEn8s1+n6tnM1KoVZX/zfmdlhk0zOtKvtc4QmX+FcswHbu/WNIPdzDK2po4SxvwUllL2olkPPTIkomrs=,iv:buTqVo8PRi1uSgRK9WHybFUnBHWz6bpwNY21AAkXdq8=,tag:pJ7FzGNMN8iUGC9nPFIhMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
