apiVersion: v1
kind: ConfigMap
metadata:
    name: cloudflared-configmap
data:
    config.yaml: ENC[AES256_GCM,data:jUNoptoE6agXbOLwweVgNzZlawRD0vcwRWIfg5cCOWA0ITNVwR7EHAoKv/RU3JNAlHuhJ/wPnvEGI5FSCBcBmHfMPSOV3UIjxDpn3vcwuLLjF1OWUDBZisqSgfUXpKDQ+z0acBtTL45XJ5/txhTBKHa+WsfNVknnle9NiYK8KAjIbM8o73bEQOn4STRo1wkg7c0M3ZliN6KQdc/l6nEqoK2d38iEAHLJOZhmdh0Tk0PjkNX+q6uvVoOAU1axVlfGAWss/kk0R3cqb53i33fh1QXjvBUMf3o52VIzGceSO2jw9SiZpeEkRX/HfM7rDOyjVXdxzsGZhNkrkoI0z2+VbTyFu3H2+AVu6N2bOO8YbEw1L4wBHbD+b4YZL9IimEGBoPJxujYsyeGOGzVf0QYvwUYI0DLHxUqgAoYqrHSu1pVnnOxxHBsZp7Uw9UYOE6Fo3ho4jzSSCg==,iv:t2AFWi9F8rXy2LKrrU0+TEMuM2cPKoYD5AxOum6lsow=,tag:gO1jQ70DQz3OKUT5W8JDkg==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQlFsZDlNWE9nMHk3eHJn
            aUtBVFBnSVpsMUlZZEZSMXp0RkVvOGExTERzCldZbGFDVHN6OEJyOTlmY2xhN00y
            UTgrSnZZNnp0OWU4WmgzY2pDdmJUcEUKLS0tIE52OEZXOUI4SCtpQlFtV21GaXNv
            WFN3Y1RxS0xtdW9uTnJLUzg5b2N3VTQKdKXRjY0Jxuew3npPOTdrkyHvkkxgfiGi
            1HVlXcw/zOZzidzG18/6auusjsfAWgzaKgr+Gb7q34PgCWXitnJ3eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:12Z"
    mac: ENC[AES256_GCM,data:u7Gwk+MW4hp11KnmV9XGtK2rwbvyky2Vr+Nz8PzfNsMqvSLLS34WCVwpUUW8x8ZCtzXjobddgZYWDZDvhxM6NYET2qmypwPLRpAC/t6PD3hsdxBzqaT0GamL/ZR6us5tnfDIV+5SEvKhuyJGeU8+k9H2UuSl/DiPcrYeq3ZL/Bc=,iv:QHrOxI85RM5/JOFYViYhIQc+I6ImMqUGw/Z04ZVbrtg=,tag:0lfydxEtkleITJWT2+OeQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
