apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:r/B0qXEy4xoPI4P4XuY0s514wAEVe2qd4n/c3PDfvoZDIjTf,iv:eFLBv+9ZyL54qe6NvJeImJthrUs+w5/g512JT3gweoQ=,tag:344eYyjb6yye+8s7HQAelA==,type:str]
    credentials.json: ENC[AES256_GCM,data:QqdEMGg2VcL8Ak9OPcLzpvz5I07yLjQ7w3hpe53qGb5c3xPpT3CIAuJOZksLYoTHd3lsfZPjD1Vd70VeyYGmhYFTpoCQf2ACvqo/sBPsUilrkxj+76oVwwJJvq+qVbSVRy7gCxQaHuNHCVHx2A56NmYKKzbpv6m+TKpnjDh+XKeNJ6IN8lCK4guz68Y6Q9Tsk2Esf5Wx2DMC9UqfuS9vvsop8n9K4OZcr8ds/9Ib4w==,iv:pho4Hmlui6thvkWlkx4RsBO6Wd+YnGNp2wYpkl9qzWM=,tag:qYvxCzmbao+U7glIZ/MwQQ==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ3hzQ04wOUNuWHdaR3hR
            R3RKZmZmcmJmY09mcElEaEpya2tqSFB5SXg0CmFScVR5MDE5dFgxM3Awc3JpbU9x
            UU05S1k3enJLK2JBd0dadHBJYlNnRkkKLS0tIHJ3dGZVVUtVQjNmYnJ2MkE0NFBm
            K2IrM1lKWVJGOTdhdWtWRnQrWXA5ZVEK/ML/jIfj26JNQQYq3TCl6rnMVP2khcMt
            tky3b/K3AWEMZuwY3Bj763cBbZ5dgppjq5SSg5wHWbjFpHiv7OhUhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:54Z"
    mac: ENC[AES256_GCM,data:p4AMhBwM28MtyzsMjF7P6Oho+v+iMnIQtO/5BqWp8ltm4tk59MlQwYKFXnZLjBGIVc/AP/z3UFlLe+XQHJ1/W1Mi86ywjGngPF3W/vHnr7z4Cuuuhvv8BYFFZ7rt/d3d+MuMCxC1xISdHwFHD1NDQXUcI1iSz6wKVrLdo4ZhK2c=,iv:xjhF+OgHDAem7+971FCBQFvBcrqdXA4i62yeNhx0Rps=,tag:2gc4RDAwdITfvx8xDKURGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
