apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:VRNR8OI3eUgJV4xn8rtcxbNM9QMzZUXXxHr+Kgsj6f1Z0/Zj,iv:DEXnWrxAsoTKMI1tEaUtr8egR9xVNowXI6tCa/YLao4=,tag:S+XPoiTVMQDayJzTeSO1FQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:JB3tU/v2QSnDTg/dQMvt+rGIfn+Xz6TtPSHSV/VxoA/CiXv04Vk8AwxzsM3PxRSVyd1yv3H++c/1sgY/6BU2McbAj2VVEImYLN/GePecSWcBbL0WuiZYnJvpj6Ld+HX5iT5qtIyGSNum5faCcw/Etx5P76rWDfkP0ePfAWom/QcIZCKMzYcehfWl5RrsDUE+dJOOkYR7gfkJKvh5DqC3SJnTL/ubVgcIZx2QXgFk3g==,iv:Vn+j1o42B3z6cA5CwecDtAdwoZjQdO7wRx0KStEm3Dc=,tag:iO39wIm3A95HAKkMy8h4nQ==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK1VRNVhDb3MvdWR6S29q
            cjJhQkwzV1FXTmNBR21rcmRIUVFHOTlpOXhZCjR5eWt1Qllxb0FraUk1M1N6VURK
            bUcvSVZUMEh2SkhGRjZLcTdqQnMxd2sKLS0tIEN1bXoySk5KYTRrWXR1c0U3d3Nv
            cUxVek1ON3lreTB1dlc3OVRITGFCZGcKgQUap2zUsmj2ZVDCDOk2IE2iQjdiXqO8
            UZzZIUtw0yE4IRUqjanFQDEj2ZYsBnstdXW8LCdW1UoFR8RxTyXPsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:12Z"
    mac: ENC[AES256_GCM,data:w6n7pMARjAMWS5CgVZTL8fEZKTQe9ovvAvRLlRZcFoXPcvV07NPOdX2eRfO7e3Pws/U6mbtbApszgmk2RwkcQus2JVe9kILPMxOt5D2BzIyIty5rLQnCZ1MMm1DawNjvOenxK0ZcDDflXYGYYVNoZWn/9PJ2F6cwW5LfUdYtOGU=,iv:eCDUpS51KHe2gKZOj3GH4ejZGhR99rwdDHkZIHMdVEg=,tag:Z+yufKfha8tZK6aON5bbtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
