apiVersion: v1
kind: ConfigMap
metadata:
    name: cloudflared-configmap
data:
    config.yaml: ENC[AES256_GCM,data:c+l8fq2FOpsXW6i7tpbFsWd7X2C7KjWyhiuxC7bPbP9D++6yWvLngMBv8chQF44cjfvlNdFa0BhntS3mLUjeqI07NyFpgOHNMJY+UU5fY7Q1q2vMpDDCFEjF+HZ966Qv+BDFm6WxvvfYxzORZews1mk2mVNGwd/5Y7YyrWqNwP6n1OLwnulT6vyfhB18vjj7xSl+DK0wR4hHSGt51apGCqaH6Cesp90CEUIxQ3zxIGaNxePGYs9CYYVey7vyr0U1nsEhg1merbeVnOAC5t6kFMCNdMyYKfyCR5k6kMDY+KOASEsBByYMpksNIVfBDmSCcE+rs4UUy2Dn9UDVTFtKs/pG8f4obx6sXWuublNd5a13Ug8do83mhD+SV+6dFwJpTeORvqyNK99bgDDAwZRxwpIZJm6QXThefoSjhZlr0CKfLW6PBKYlJ9oL5OV29KnIs2+2ftcV4w==,iv:zAzLSokWAVAnsBEZsbDQIKhl6C9rLEt2hFgHRSM2kak=,tag:4b97TJFixSmWjmjkbHSujg==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN29jYjBkVXh6TUtibTc5
            K2pxVkVqSHMyaFBaa2tVa2lialpPOVJYdFNRClNwVlRTT1BTbDV6cm15T2YxM2hZ
            T2FoUVVsY3JwZlAwY0RHcE1OckNheFUKLS0tIG5VbGNKYUhLTlo3cUFHM3Z2NTdL
            cUg0NjFmZ1BTMGQxdTA3M2dNb2Nxcm8KEUucqVcpukC/OUPIUEX8pXX1NuLMX7Ea
            lat2VTHM0ft5OH4KUJ3EEfjA13bMfYCZU9yJ0ycJf9IKVBzwAv/OBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:45Z"
    mac: ENC[AES256_GCM,data:0G6EWYuF9mZOwQaTHzk9e0zH0lXN0u9zl+31dwVxaaYnAsz7PGGdpzvnU6tTq0SgD5FNJ6FMh+pM9Eed9ZbbSwyaq3nr/+m0kKjEavpKn87QHIlHGaV7Q07SpiRygYdMmxnqKU2+WN9K4hbKoefXu0SnkttdUW2lMrzt5ds1oOg=,iv:9oGc7jaXnKDEnMqAvwKuub4heCxrAHK3R+9PEp0Hno0=,tag:3BYSE2he2Aiaj8L5OTsjsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
