apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:wcxpQKus5/mJPWxPEC6We/cqfU3jPWZMtBr70K3NmnuzRG54,iv:6TssJiSA5SnM1bUisW92HOUfMW+Z2VF8CZXOyvWv7aI=,tag:d4xcW4nB/A+dJ9aIZMu34w==,type:str]
    credentials.json: ENC[AES256_GCM,data:4hlJ18dQOtP8Bzec8gIy3yKa+0NWyO3zibpJcT+n9VjoxtDa5JKVnRM1n5oXL2zt1bUxwpKW0ZccCp9O6g5ujM7QeM82b6RqMEAW0oe4AAYuLsYEIvvFiH62Yf0QW7yY6EIdbft93jkomsuDEtT0DFsLG1aEThUUyAbtl4jKTOMadDEokVLj5Z2xP7z8WF144wrcstxEJYaivUhqYewXUsPWZ82UKyi8o93YXS3dFw==,iv:2VK9/klUbCI+IdIValMWtAa2xHlv45b7BfPGfO2GBxo=,tag:WswuDXopG4XQSJicqsOKTQ==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ3VoQllHR1J2c2hpWkli
            RWZLUFFoMmF6Y2FMYk96cHNIbWpuQmJXb1RRCmlkZzBOOHpTNTJZMXRiZXpLZ1l4
            WTYrRzlPeWVGT2ZicXkzcVowRmg3eTQKLS0tIFZDUTU4bjI1WnM1Y3FWcktFTGlK
            WUFRRXpVVU1HSUxiZ29RTEVxa0ZlckUKm1HwdlSwzcbas6wqGZHzTixym38/5WMB
            UH0V7nnwl+9OEafuDa8s2l8pbl612xGDZNls9/86nt6UjfCo7urmSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:45Z"
    mac: ENC[AES256_GCM,data:9X0SXMRGVKMSMV6MVF0pB24Inay4EpYC3XsCMbKoKtPtHmXB5Ga+vwTjo9cYWMrEICm5BZDwJkAXeuknDlpIdCDuNynqEXParNtGBubV+++3RhxBXV3byadNazUS3Oz0VxZQp+1rw0ef29ZTSDZP9vpT5ByRnf/fw/MLuUDUF4E=,iv:G0oPQfoVjlem4wFwJ9hWKffnWMuPHqK5Q0zSr4exr3M=,tag:KDI5T71cg9BSvUUhUuNP1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
