apiVersion: v1
kind: ConfigMap
metadata:
    name: cloudflared-configmap
data:
    config.yaml: ENC[AES256_GCM,data:UMF1tGLdaydHbD+S94NbzuQHmztaVEt0xkWW3CBoz4jOcLAyDUpw0Ya1R1P5d6Bj58CG7nYjT6finG4A3ER24+t2idCaenGd2SmSMwpawMjPY7ADmxSOI9TDcf26gf4hqd43+YfpMmiDyIPtQlEiRbEG++SdnKbQXrVGP7j482BmPmS5N4pgdrXwUoF7HbLZxmb3Ux0qpPQYuQ8O+l9Fx40/Sym/E6RwK7e2Zh0g8oPex7Sy2aplyl4IMCOaXu4gEOUQW8ORVQgs95ATjnpD0YMwlDv1Nt5eH/BGVBmqDCfItst6HCQh0PzrvYUVN9ad+rz+1wgU7dmmlR05mtOtOnbYwLBdvZswHy/EcieUuR/ZZ4sHV7zPZtTmtqmNIHX52HudkgoPs0LFO4o7X6/Nq69n5NorVPQM1Mstq1A7CsRt+WkeT+MhCx/H9/IsrI0C+O3QoxMDxQ==,iv:fsj00aUY4yoTtHA1vTjU3Gq71m36lXHahkAnXV/0+3k=,tag:g3uMqDDr3+AD9Wnj/m74Qw==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTTVUcjF3aDRxOStWU3lj
            RHh1NndScW9jTXZCaXB3OGhXa3NlM2YxNnhvCmVpYytydldkWnVsV1VuUkNiZTNN
            bGxXRzdza1FsL09nSkpkb0lyczRSTjgKLS0tIHRSUThVaXJOeERTRURoM2cvWHEr
            MHZVbVhHWHpFM0w2ZmVxeFZPSitrWFEKE/XHhCGux/r0+pkcKgNJox3t0Oz1mFNE
            3QfgP5+IG+BZK5knEgxnlB1na3qpPvEevjj1vt1++S5bNirCavkzng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:54Z"
    mac: ENC[AES256_GCM,data:symZjsC6k1XNspxMXrMEvNsyLlbLT8bedumA5MZInLRkmAmEYiK3YZmrYdC2Pq9StXDPJMNC7h9EGMXp0tKTZDK5s8dR5KjU35ZDqY0aBsk2crTeSRzfeNZBNjpzZNeznue9zuLkQAI3ceMgKIQUm+ZPXpOxlnnhehB+1CivZ54=,iv:nYqC1M8usH8SJTp06c8bzSRAnPtExqQAqhrhs2QFtTM=,tag:XrUpeLGB/sv26eF9a6JkgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
