apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
    name: cloudflared
spec:
    endpoints:
        - dnsName: external.gitlab.be
          recordType: CNAME
          targets:
            - d1ae206c-f43b-4d43-9dc0-39c273c60b45.cfargotunnel.com
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SUFNUDV2SWFFVm5uNVhm
            T2hicUNUVkdFTmpVMmRkM05sL1NuUmc4emo0CkJkc2Q0cWdNSmxjWE1aTmZUU01n
            bGVqWkV4Q3NMQW0wVEVMRklSRElZeEkKLS0tIGgyU2d6Y1NlZzlhdDBFV1R1dFJS
            T1hWRDNJT3dsN2x6T29sYnI5Ni9aUEEK2gQSI2XiVBz6Y6pwy9ENiU/a4gWvVHxf
            lhqPRzYoH+2tEG7AxJ1KcftIgxv1XIXbhljtMQdgiLoUvmsJBZAi9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:12Z"
    mac: ENC[AES256_GCM,data:evJ5gmeetwQq3Os/Cgd2mFtxdqCG066hOvmDzNK0VWE2bk0qn3vXqxN1gPFjKq3lWm7C4HdgYAmtQ1mF5/GevGx4Zt9tO0Bi7KqYUhU5K4Rxqkw6F0Aqy/3ehn8/xUQrokEGOKVWMwva3GamozfKCuQFAJk+ybxSl5NmmCvh3lM=,iv:l25ibXRPNqFBJBjpCyLNlqP41Eih7HYsZ5sRgsgAcic=,tag:7eMGejZC1UAdTxffx9YgBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
