apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
    name: cloudflared
spec:
    endpoints:
        - dnsName: external.gitlab.be
          recordType: CNAME
          targets:
            - d1ae206c-f43b-4d43-9dc0-39c273c60b45.cfargotunnel.com
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4REI5TmQ4T0FGUzNDVjFp
            ZzlsUlFwaWQ5QlY2RnM5Uk1YVUZkdG5qVG5rCmpkVEJyOTh6Rm0rWUJHc1dSYTRS
            bnJKUGNTaTY4M0dhdnN0TXhXQk9nRUUKLS0tIGNLa09DWUREYUNvbDMrMVlPVk5P
            Z1FjaDI0VmZKV1dpeGc0dWZrOGt1UVkKFTHdiUV6kRqK0bwTXMogUuECW+mBeAqz
            TKcZqmgvxqpGJm9LYGrqZCORuwCvwT4hZSIHokbzOtDCxqytdXrAUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:44Z"
    mac: ENC[AES256_GCM,data:PJCVdfROBVWlS6zfTz95d6k77wIEsH40N91Iyfn4/o4ooqkn3GsGf1StbzuCnXBm+2v+RLojD1fAjnFWPwf3Ecky03fXxV8phTXSPQOQEH36Hl1Yvvq4mx+5LE4WEyboxWvreR6H5RilmOwwKwNW8g3QsIuL7Q8BZ3oYGcbQpQE=,iv:95s/f/0LwoqaeV74UUyHBw7wmG6Lyr+h+l+5IAxWuWA=,tag:FY2XkUzXT/W6ezUXpU3x7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
