apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
    name: cloudflared
spec:
    endpoints:
        - dnsName: external.gitlab.be
          recordType: CNAME
          targets:
            - d1ae206c-f43b-4d43-9dc0-39c273c60b45.cfargotunnel.com
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VXc4UkJaOU9YRzVNcnZm
            R3YrVStpVWVRNDErd2lnZU91VUhJK3ZpZFJzCk5oZVd1bFNiNWpxRlBEbTZ6NWhU
            SmQ5MHZrSkFPRW11bzA4aEpqaE1WVTAKLS0tICtjYTQ0K1FtakRzblk1RVJTNkJE
            djl6bDZlQkt2MXpzQ2JyTGRHL2dnRjgKX0IxwbWMOsjYONiO/uA92MuWK3B+5nOo
            7Mcsa3t1du5nBYnJvlrvtDulftDhT1FlB4RQF4aPOYl9Km8/vyc4+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:54Z"
    mac: ENC[AES256_GCM,data:dE9TlLKZuanOxMnFf73JMt0d5zHj/1me8LLTyh4eUfNr0hdXcITdLRmjq3Om9IC+nR3fpT70nyP7JNKNRYjyR9NiKeA3ixozL1uRGhTKuGByIqOmOBcJAr9bueVZs0c8TafUTIdJWsstEEQOddRajN983iomTMEXJbQM6VdOcIE=,iv:IFii0/iKTh232UEFat8EumQ6SkDYvR+zGxcB62LaS7M=,tag:JYfcvpreaJYip8E1A7yGIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
