apiVersion: v1
kind: Secret
metadata:
    name: internal-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UXi/6SxU1QVoJOt/wXI4FdOeWYcdEY4mzOktiZSVN+6muWJ3yWtNwQ==,iv:B6A5jjP+hy4uxLrAfeAabR6nDMa8W/xNzWvillIPC3o=,tag:RSvt3sgQE31cve/rlO6vuA==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwS3hVVFIzUWpOMTV0dU1K
            WmYyaXpJeXBQaGs1UVVLU05mTzZmdWdyMkhjCit5d0FhSWdnRlRia1lhRWhkMkt0
            ck1OWjUvR3ZaT25WdFVwUDE4WXFXUjQKLS0tIFNFV1JLcTF4Q20rUjRXdXVkb1Zk
            OEp0V1l6ak1saUg5RkM3QnZtSm4xbHcKvpUAFckNkGEDpH2bFMEzAIli7coWc0Zk
            gWm4EMY+7oHH1LlZWsNHJoFfzaKFDvpU0KCoUbuCStRS7nJfVRJqdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:11Z"
    mac: ENC[AES256_GCM,data:wU+2dDoGFjOQr503gDrlSD0ljt6CkLwVetvHpixSM0XSnAsm3mnmcokRFC5gJS5pEhlL8Bmj6EjlC82zZFECIifq1k2YR4HfqfpHyJhpHJThJpVymDzK1emkHE2OeB5iFf8JCEffZ52JTJOjpbQwPaIL+pHKQKdWQ9YkC/MwS5o=,iv:WYgoeloYg9WuZJV/yzF8YQ8W5w/5ymLQ2pCO2FCZib0=,tag:vDiyGXKvWTBKawk1aaBV7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
