apiVersion: v1
kind: Secret
metadata:
    name: internal-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:AqvyFjzGqSkpaMY49opBh/B4L5nLzHcuz/QRVojx75Oq7rkEKRAb8A==,iv:CRUr4Qp4nVSe8CMZGzoyMw55+Tub1yH2qD7XWg8PRQw=,tag:YbT0/nLIR/iuHYySwS3SHw==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUEYvZzRTdldnZnJNSmpa
            dGNnU1B6WG5kRGJYTld0WnlsZllWb1pxTHpvCkdUMjNmMVJnUGxwL0VsV3R1OW9T
            YitEWnUrSWFXdlBiWkE4Z3ZRSkJ6RXcKLS0tIEg5QXdoRlNpMEQ2T3p4dE9XUG91
            Mmk5QmRlM1FYNDJ4VHlhNDVOVDJNbVkKwhA5B7GXIq4lk/gpS47umCPb6oyDWePM
            XcnXt5G9m6XOHF08E88qipOzof1J2jKuvn2jTlCeOh7rXoYLngy+9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:44Z"
    mac: ENC[AES256_GCM,data:DudePcmxUsg8+283BUPr65DtXLv83Kp3hSbxyMI4QPyn3IDE3MjWHWmhSsYcuv1oqjhCn1m4xSRtJs61GHzb0aQ/Y4QY8ro0h+142RbTz32CpBpAmql8ouSsdnJUxXpv7cqAB9bMXWeDtwuyVUMlndw/q7nCmrl9IfEUU2l58ko=,iv:5jgw3nuRRfl/lga8dOQ4zJyxAN8Z3Wz2QqK6BUYIN+M=,tag:g0Ept8/ZZfVH9JhBY3ijbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
