apiVersion: v1
kind: Secret
metadata:
    name: internal-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:86V1sYvyV4leIsLrJrfruTulxF0O74u3ABrnifjGOkmFiM0XQn3bpw==,iv:09Ycypt/8gm1bz3WZe7qdew7b3QAbePfYJ26gr5NIuA=,tag:Uej/vub45WFyPLgWQha2yQ==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU09lWE80WTl2a1F0THJE
            M1Q5R3pHR2huZVQ1M1VhcXhPR0VGY2ZNZkZZCml1SVM1RHQ5V2dlTmhGYURaWTJH
            WGx3OXhGZDl1RkI4VGQ5ZFM4R3JReXcKLS0tIDFKQ1dLWmp0S3RyVjBLQnp6bEVs
            WG1RRitaTmtEckRkQm56NjF5dWZFejQKELsvhf9u2ZzBJI2oNMleppQ/S0bkBj8E
            wg4qJ+jiTy0XSzf76v6JlvGc0BdJ2eZiINoMs2qbWnk+6Y4vuNuYDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:54Z"
    mac: ENC[AES256_GCM,data:xoh5J88QMHgnOk2YN2MaYkQijK3nNB4x6Fz5MDPxYc2a7HmSjK+yAQGY1RzVHMi4HKr3TMvkL79fp5xR/ZMBOcFkYMB68gZ3LWeIvsFHJc0JEu3vzlwPc+Fs+pu6+o1Hv1cPJ0NlFemAinOme5rFLVaOh00V+71WfLaz8zZ1SSc=,iv:33ZKd8Jp6eU9NObWVMNgSSrzGop/Be3286UYFzZFFJw=,tag:ipZO19SlBiNNJxEwNePdEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
