apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
stringData:
    password: ENC[AES256_GCM,data:hjd7pKaPV/8J,iv:PV0FUIzQClXd9d/GUrr0YTPReQ+GHEwRF5Cn10ImxtE=,tag:iLkWuKPutJo5eclIZpG63g==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbG1XVDVFcDRJSXdiamFW
            U0JFQXdxNHFibks2bUltTVZaK1hMbld2MFhRCnhmK2ZZS3R3ay9USm5YU1hqYVhr
            Nkx4cTRkQUU4bFRFNTVQQ1ZVSHdqdHcKLS0tIHR4UHdNUTVQNTBkdGEvOURSeFRq
            R3k1QUEzT2tObXFxbzZLVVVreEx4ZEUKxWVVdAOO2jabJf8TQ+bDWrB9yp1rpaCv
            LRlm4Mbe2ej3DvaxkDNvU0t+dYyUjvaF9RKtVVQELoR4jKsw24gSvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:12Z"
    mac: ENC[AES256_GCM,data:4bYt/Q8zEFPqUftJ9zRwossNkKtMcGJhG7yFyydVwrAUX6OckK56eRUyf+qDzxHleXC47naHjIHzlDwkbDU9iujg+HYqDmqS5bgG9AX6GY4ZVqEwYtaBa1NyyIevx+Df/lf+FL2DD/KoNd0IcHpaJ3To4H21GBFFUPx1imZgs4k=,iv:jL07U1B0V3aePjs7fvCAtSqO3iNKk26gdtjo1c1N6ok=,tag:TSZAqLNr3twD0bk9eaDRbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
