apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
stringData:
    password: ENC[AES256_GCM,data:pRANtQM7ZJmr,iv:ILPIWp8uuHIsK1vyKLObRT/vwnn9Sxps1IOhW6W5Gc8=,tag:mK1hwTKcQTR196PxQxdOgg==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPak9MN1dhb3RkU1hReVdL
            WnQ3VStqKzNBTm5Nd2xtVUtlWUJoOTgzK2lNCmpZcklCQ1VhVldCKytadkFGM0hw
            ME0vL0RDcUF4dDlLRFBFNmxxRE1KbVEKLS0tIEJORXhzeU45L2ZVMDlPM1B0RzUv
            NGcvNFp1Z2lGbWFhZWlEWEptVHJNa1kKVIkSQt9iHKooUQF0FWIxeOpG7LUaPKRL
            Z4bFGVYyhZK+KD81QFXDkZnqeC5MSSaJ2imvc3Hef0e+W/U81OMk5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:45Z"
    mac: ENC[AES256_GCM,data:hqrI7eFOo0BViox4qP+LdxxSunVAiVM2XlObV9wAS0Im4I5vHDlTZaJhN8RNVkOZNNZZZZKRkcDoePf1q+t4v/f9bjDJgFc8Zzin3bsjFa/Gnqlc6GmgE0WnrLl5CYQL2+WIezcl90ww/Q6rwkwwCBt9rag7J3mqKj/TF4VoxeU=,iv:fWjjNb2aYq9OQu0YpmFZpfGrbmYTUy57QbrcmtLPvI0=,tag:WIcWcxS0lFD5HfRNodVtKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
