apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
stringData:
    password: ENC[AES256_GCM,data:Z4btRGlsVatw,iv:QMciFkGjGc+Zpr1nhq2BCmbJ78KN7mWWtsezkQ+uORw=,tag:MLtd3MxvngU5mcXFhQgxAw==,type:str]
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRVI0V2xNMXdwRVpZNGtL
            MzR5TVFFd09XOHMxU0F5NnhKUkQ3WlZseEdjCnFxZVFkNVBsYVZXQlB5L1ZHd3ZD
            Z3ZwdWxPeU1uZFNtNGVVa0NFaGo1VDAKLS0tIHRFVUhQenlETE03WFVqbUEwbit1
            RzlnWHVMSVorVGVySHgrREE1TnNhVFkKtshTse1vTWMhvueZ/9A3zYRamSd81ayr
            QrDPwJ0S6mgcWyU8Q67Cgc6gWkTqlo3+I6awQCNqDuawgB4w1/jDOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:54Z"
    mac: ENC[AES256_GCM,data:uji7WtnThj+FaMizYILbB6SH88TqJot8qnhtpDTPbJxLHlr367bCcj7JEKf1Hor/8PHJWhZ1BW6MGnaUjUl49u9qIyt1YQGW/TwhtttP9yBCg1GgCq+Qpk+DjLnrdNG6/kDNsxEnQxRc/V/kllfDagfwiShleaf2D3A2ECSKqpc=,iv:/ZQqHvRzm1Iw8bPM7tF0JLHfy0qwjgkmJtPj9+8SKaQ=,tag:HteqSEdaOLETsFSmtinw/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
