fullnameOverride: k8s-gateway
domain: gitlab.be
ttl: 1
service:
    type: LoadBalancer
    port: 53
    annotations:
        io.cilium/lb-ipam-ips: 192.168.1.22
    externalTrafficPolicy: Cluster
watchedResources:
    - Ingress
    - Service
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dXlOSWFpejJKK1pXbndu
            UFY3Q2pucmhncGpOWXlyUU1NQU5VZWh5MEVBCk1KUVNCbWdORkJ5U2xTbVRzK3pH
            cGhxdzc4VStEck1wakc4aHVtMTNmVmcKLS0tIGUxWERzSnRLVERaMEZlUktRSDNH
            TmxNcmNkYmd3STVNbkJiMEZGV1Y5SHcKXvVI27sllBul4EOqIxeYvGuVHAvUAjfx
            Y6lNximdMXc8iXW67VAEI69gQfA0S0xqG8mdKiqUw1fZHnRHvyljZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:54Z"
    mac: ENC[AES256_GCM,data:IyF8ist+Rhkls4aQL/d6UHoQVHoAIEgNcdvHagnUK6zc+MuN1UTWDxoH333VRpONxX7h6vZtNvRDb9xRQh6xio/jyf0+aGtr3d/uvLRc/OyQvU5WnE7AcrUTdokGwaZqeKPjvLIV6F7lIi5L5IrxpDIbMoID89CsRM5Tvdomovo=,iv:aSJDP2QmBR8/pPVBULjezVhe0J4RtBoSXK678F4Cjh0=,tag:0J2ObC/LbbVo0z7Vh2Ka0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
