fullnameOverride: k8s-gateway
domain: gitlab.be
ttl: 1
service:
    type: LoadBalancer
    port: 53
    annotations:
        io.cilium/lb-ipam-ips: 192.168.1.22
    externalTrafficPolicy: Cluster
watchedResources:
    - Ingress
    - Service
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSE41cktrYkw4bHFReDhZ
            bDVuNkcydTYxbzN3TEJTb09idkJVanYzR2hFCk1hcFRtMWJsL2tYK0tseFkvQ1E4
            UUVseXprVkE3ekFTMUppRTVObE5jN3cKLS0tIEE3L2ZITTIrUDhadkFGM3lnZnVO
            UGpHUGhWWE1Ob3A3eWxuYUlMMlB5U28KVgLHqwFJXfsBey588uBYRdksIe8ooPZc
            GIXGCKEhtx5bkrT8618ktxemYtN04XTMcU9AlpkuLfJYDjHluAxz3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:44Z"
    mac: ENC[AES256_GCM,data:DcRc/ts2UMxs6sw7Af9qE9sRJaJOGldcUFsXb4XycP79gSwGt7xLpIGsqu0Rrgy7i96olc5XkNlOwDVlBmFXEFR6LVdUdP0Aun6+9ic0bkdtSdEyc+YX/KoXL3N4KChvDDZiF0RPePWkfQk/3sQnN6d0elFwk0UJ7yWKOTjTU4A=,iv:9Dt/NWRNkM+tId1uK5oW65JTNvxU14+JKbcCApryOyk=,tag:JGX/mxYwGcQiXNLwVVTatg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
