fullnameOverride: k8s-gateway
domain: gitlab.be
ttl: 1
service:
    type: LoadBalancer
    port: 53
    annotations:
        io.cilium/lb-ipam-ips: 192.168.1.22
    externalTrafficPolicy: Cluster
watchedResources:
    - Ingress
    - Service
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaytrWm9EU056UUJwT2R2
            Y1RiYVpJa1lkNDE2c0dDRHNQeDU5TkczSFdzCkJGcFNSZ2ZHRTdCNnljTW1ZdU45
            Y2tpV2pzV1FTN3RScGs4NHBCcTBmRkEKLS0tIEw0NHBKcWI5anU3aFNpZ2FiR2ZO
            c1RXMk9LMkpzYndSQkJ3WGlGaWY1WDAKiFRtOc9vjjBPq3CsL5Hh5nckZe5o1RdM
            WdKfa3ZwscAgTLufE6PiAfzYK5TE0YjuDGGzHM8e30p/6G5CGSbADw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:12Z"
    mac: ENC[AES256_GCM,data:lWKOzpul15oOghU0d4UXUY0/Urucp+aSb1n9L+/9T0tpLEb1LrFg5jl1VFsXvz3oY7TlsxmkrQ5Cuyu3Y9z5TaqnsLrdQkpyvc130g7pvkl7M4So8UAam1ahOXvTO853Ig8b//KX+UfCwQuyleD2mVpFMXvH5yT2pLn2iOjh/wg=,iv:lLmQ5ye0yufnH4H2x26n/dj3k5iL3Gas3FHt/ReW9+s=,tag:Cq0s9g6aX8nD3useR6tcVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
