fullnameOverride: internal-dns
provider: pihole
registry: noop
extraArgs:
    - --events
    - --ignore-ingress-tls-spec
    - --ingress-class=internal
    - --pihole-api-version=6
    # IMPORTANT: If you have records that you manage manually in Pi-hole, set
    # the policy to upsert-only so they do not get deleted.
    #- --policy=upsert-only
    - --pihole-server=http://pihole-web.network.svc.cluster.local
    - --pihole-password=Aveve2008
policy: upsert-only
sources:
    - crd
    - ingress
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
    - gitlab.be
serviceMonitor:
    enabled: true
podAnnotations:
    secret.reloader.stakater.com/reload: internal-dns-secret
image:
    repository: gcr.io/k8s-staging-external-dns/external-dns
    tag: v20250510-v0.16.1-151-g2f165e87
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVXBDMk5kTGFrQ3hMZjNx
            V1dDZUNLYkdpZ0tEbHVydld3VkgydGNKb3lzCkU2WkxGcXJGTHRURk1lcCtrUGNN
            TGpCK3A3U1dGRlM4WmphaW9sc2E4NkEKLS0tIGt5S3R0WVhRZ1JTN0xqUjUwdjlS
            UWFFbmw5d2MzTStzYnZBTkx0eUpHUUEKZceFsJDqh0u+A6ODCxfd0h5kMFoKxS+A
            tc307IG8VoOefD9Jk4M4xlH0ehrfckAWPMGZWWad4TQw/qJvychTrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:20:44Z"
    mac: ENC[AES256_GCM,data:nAKotYw12CB5GnsomncN6Bzb9cFjtw5XxmErPBwp4BnY9+JoKwadssHt43JPOQgx5Lsk+wuNWFqPYoJrhuLYxsOxlW+IRCjEozM5d/+wBs0zEbxG6/lwJbq54zlJkuCHvOd6ajIMsXDF6ZAic43JbKBqtRioAFr3jKjfMf8Qj5o=,iv:eAjZrVvP1whJKkKYw/ppp7JJgk1ReuUpAJcw47J1CQA=,tag:BRPZHUheplJDWOWyQJ6K0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
