fullnameOverride: internal-dns
provider: pihole
registry: noop
extraArgs:
    - --events
    - --ignore-ingress-tls-spec
    - --ingress-class=internal
    - --pihole-api-version=6
    # IMPORTANT: If you have records that you manage manually in Pi-hole, set
    # the policy to upsert-only so they do not get deleted.
    #- --policy=upsert-only
    - --pihole-server=http://pihole-web.network.svc.cluster.local
    - --pihole-password=Aveve2008
policy: upsert-only
sources:
    - crd
    - ingress
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
    - gitlab.be
serviceMonitor:
    enabled: true
podAnnotations:
    secret.reloader.stakater.com/reload: internal-dns-secret
image:
    repository: gcr.io/k8s-staging-external-dns/external-dns
    tag: v20250510-v0.16.1-151-g2f165e87
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidHlhTTdnRm1BQXppTGtr
            TE5YSFJQQm55RVdlcEVaMVRGU0VQNXZGekE4CmxOVktJdmtWa0RTN3dsYlVsVnh4
            djZralhGV0JCTnF5Q3g3VkZwbzZ5UVUKLS0tIDIvS3dqNmdtNWcvVGhOZkZCYmlW
            THZtQkFla2JmMW5iRWJudDkvc0VnUWsKJMh+O+oDx15tFaBpTloL3LjypbL+UPYT
            bmTYTkj7BQj5QjFqM7ZUFXOeYFh1Kzj/joH0EyCzzPzIsTtmc64QlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:10:11Z"
    mac: ENC[AES256_GCM,data:niXySeZ0zWyqmuwpRuJTMs9mHTQlNPuTlIC8qxT+XBjk3eT0fNq81Uyv71xzNGIk1CMKH9NlRuu8GDNcTqV9GjSNksuW/yfxj8m72hPuBKRE5VGwkx+jZLKOh1n5jQcgoLF3FeVXb0lazx10UGD1MUOXUOZ33frzYLDIZgmbRRo=,iv:ROJBivU5Cbk+eqf+KPGVWjl9gZZ/gqdsOo8/JsA2sdQ=,tag:AlLat+QxOjFwNTbbdq/+ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
