fullnameOverride: internal-dns
provider: pihole
registry: noop
extraArgs:
    - --events
    - --ignore-ingress-tls-spec
    - --ingress-class=internal
    - --pihole-api-version=6
    # IMPORTANT: If you have records that you manage manually in Pi-hole, set
    # the policy to upsert-only so they do not get deleted.
    #- --policy=upsert-only
    - --pihole-server=http://pihole-web.network.svc.cluster.local
    - --pihole-password=Aveve2008
policy: upsert-only
sources:
    - crd
    - ingress
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
    - gitlab.be
serviceMonitor:
    enabled: true
podAnnotations:
    secret.reloader.stakater.com/reload: internal-dns-secret
image:
    repository: gcr.io/k8s-staging-external-dns/external-dns
    tag: v20250510-v0.16.1-151-g2f165e87
sops:
    age:
        - recipient: age1fyc7uux0krx5h9hxsvc4qvh4hyxut9zk6zvxf9g4tc2388ut6d9spqh370
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON3dIWC9xa3BDZ3FacVpz
            aE1URmVhQWQ1eGp1WUFTc3JsdWR1M2k1OW5RCis1dWRnemxJQ1BTQkF4TWx2b0tG
            T093ejNiUnpJNlVrT2FNQkt3YUxaT1EKLS0tIHVwYUR1aEtBd2luNHhPUWJzaE5C
            UmM2NUpZTisvbkYzL2NZZDhCTmxaNVEKHLvkB6vUfquX507BVAEcu/S4o7MsVcDT
            v0mCsnR2MZRZW9CS2ziGLdU2rmUDQpdkbXDbNjiBRnYmDhjEoGNc2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:15:53Z"
    mac: ENC[AES256_GCM,data:4jP7ifoDte4et/wN1n9z0hcKsYiL+xENlbrrIccebyVar0BFC/Qk7DxiLp0jasOMVxPMPdjDp5hTLMEz/avYdj0/whzjbDlszBMOYbYMBIYRru4mK92130TYZOTOzvKJ/5ZH2Tg56gCGCjHXQjsV3guuTmkwz92VZqlL6Q7/uvg=,iv:7cLS6D6keVH+3rzSE98msfLR/RfLU2c5TnuyLOu4Hm0=,tag:JpN5Qd5OSXR3iOqXEIK+Fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
